name: lustore
version: 1.0.0+1
publish_to: none
description: LuStore.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  desktop_window: 0.4.0
  brasil_fields: 1.1.4
  http: 0.13.3
  get_storage: ^2.0.3
  extended_masked_text: 2.3.1
  flutter_easyloading: ^3.0.3
  intl: ^0.17.0
  jwt_decoder: 2.0.1
  jaguar_jwt: 3.0.0
  flutter_staggered_grid_view: 0.4.0
  syncfusion_flutter_charts: 19.2.62
  file_picker: 4.1.0
  cool_alert: 1.1.0
  flutter_launcher_icons: 0.9.2
  infinite_scroll_pagination: 3.1.0
  flutter_typeahead: 3.2.3
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/logo.png
    - images/avatar.jpg
  uses-material-design: true

get_cli: 
  sub_folder: false

flutter_icons: 
  image_path_windows: images/logo.png
  image_path_desktop: images/logo.png
  windows: true
  desktop: true

